FROM python:3.8.6-buster

ARG DEBIAN_FRONTEND=noninteractive

RUN pip install --upgrade pip wheel poetry setuptools

COPY backend_services/config_manager/requirements.txt \
    backend_services/config_manager/setup.py /app/config_manager/

RUN cd /app/config_manager/ && \
    pip install -r requirements.txt

COPY backend_services/ml_worker/requirements.txt /app/ml_worker/requirements.txt

RUN cd /app/ml_worker/ && \
    pip install -r requirements.txt

COPY backend_services/config_manager/config_manager /app/config_manager/config_manager
RUN cd /app/config_manager && pip install -e .

WORKDIR /app/ml_worker

CMD ["rq", "worker", "-u", "redis://redis:6379"]