FROM tiangolo/uvicorn-gunicorn:python3.8-slim

ARG DEBIAN_FRONTEND=noninteractive

RUN pip install --upgrade pip wheel poetry setuptools

COPY backend_services/config_manager/requirements.txt backend_services/config_manager/setup.py /app/config_manager/

RUN cd /app/config_manager/ && \
    pip install -r requirements.txt

COPY backend_services/ml_worker/requirements.txt backend_services/ml_worker/setup.py /app/ml_worker/

RUN cd /app/ml_worker/ && \
    pip install -r requirements.txt

COPY backend_services/app_server/requirements.txt /app/app_server/requirements.txt

RUN cd /app/app_server/ && \
    pip install -r requirements.txt

COPY backend_services/config_manager/config_manager /app/config_manager/config_manager
COPY backend_services/ml_worker/ml_worker /app/ml_worker/ml_worker
RUN cd /app/config_manager && pip install -e . && \
    cd /app/ml_worker && pip install -e .

EXPOSE 9000
WORKDIR /app/app_server
CMD ["uvicorn", "app_server.main:app", "--host", "0.0.0.0", "--port", "9000"]